# Generated by Django 4.1.5 on 2023-01-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_details',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
