# Generated by Django 4.1.5 on 2023-01-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
